### ISSUE TITLE
Labels in Readme.md in wrong order

### ISSUE THREAD

**Issue by BlueWinters** [Tobias-Fischer/rt_gene#10]
Abs: README.md errors?
I noticed some description about labels in **README_Dataset.md**:

> ### label_combined.txt
> ...
> seq_number, [head pose: down(pos) / up (neg), left(pos) / right(neg)], [gaze: up(pos) / down(neg), right(pos) / left(neg)], timestamp

I compare some images and its correponding labels, and I think that it should be this form:
 [head pose: left(pos) / right(neg), down(neg) / up (pos)], [gaze: right(pos) / left(neg), up(pos) / down(neg)]

**Comment by Tobias-Fischer** [comment]
Hi @BlueWinters,
Thanks for reporting this! I can confirm that the current order is taken from an old version and needs updating. I will check the precise order soon and let you know.

**Comment by sahilrider** [comment]
Any updates on this?
What's the correct order? [gaze: right(pos)/left(neg), up(pos)/down(neg)] ?

**Comment by Tobias-Fischer** [comment]
Hi,
I did a quick visual check, and I think it should be:
`[head pose: right(pos) / left(neg), up (pos) / down(neg)], [gaze: right(pos) / left(neg), up(pos) / down(neg)]`
(note that head pose left/right is with respect to the subject's torso)

We plan to release a new version of the dataset in which we will label it in a less confusing way ..

I'll update the readme for the next release.

/cc @ngageorange

**Comment by sahilrider** [comment]
Thanks for quick response. 
Head pose is ref wrt subject's torso, then what is the ref point for gaze. 
Now at the time of inference, gaze incorporates headpose or not as I can see headpose info is passed in the network. My Question is if I am looking at a point, then I get some reading for gaze and if I change my headpose little, will gaze value changes? 

Hope my question is clear.

**Comment by Tobias-Fischer** [comment]
Hi - it should be called `eye gaze` - so ref is the midpoint between the eyes. So if you change your head pose, your gaze values should not change.

**Comment by sahilrider** [comment]
Thanks for the clarification.

**Comment by Tobias-Fischer** [comment]
This has now been updated on both mirrors (box and zenodo). Thanks @BlueWinters for reporting.
