### ISSUE TITLE
MPII dataset and Image augmentation

### ISSUE THREAD

**Issue by uestcMeng** [Tobias-Fischer/rt_gene#100]
Hi, I notice that you use MPII dataset in your paper, and employ the both eye patches as input. I find that MPII dataset contains 1500 images of the left and right eye respectively, but the left and right eye are not paired. And I also find there is another dataset called MPIIFace, which provide full face image, so I wonder whether you use MPIIFace rather than MPII.
Besides, you proposed a method of image augmentation, "we perform 10 augmentations by cropping the image on the sides and subsequently resizing it back to its original size. Each side is cropped by a pixel value drawn independently from a uniform distribution U(0, 5)."  I have some doubts here，do you mean to randomly crop the eye image ten times and then resize it back to origin size?  Would you mind answering my questions？Thanks a lot!

**Comment by Tobias-Fischer** [comment]
Hi @uestcMeng, many thanks for your interest in RT-GENE!

Re MPII: I honestly can't remember. From their [dataset description](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild), it looks like they provided the eye area with corresponding eye landmark positions for both eyes. From that we probably extracted eye patches for both left and right eyes.

Re augmentation: Please refer to the [code](https://github.com/Tobias-Fischer/rt_gene/blob/2740404431e5853f47a9fc25e4ce339b2bb6953a/rt_gene_model_training/tensorflow/prepare_dataset.m#L167-L292), which should be easy to understand. Let me know if you have further questions after checking the code.


Best wishes,
Tobias

**Comment by uestcMeng** [comment]
thanks you, Tobias! Your reply helps me a lot!
