### ISSUE TITLE
Prepare dataset scripts for MPII and UTMV

### ISSUE THREAD

**Issue by martinhoang11** [Tobias-Fischer/rt_gene#102]
Hi, I'm looking for prepare dataset for MPII and UTMV like (prepare_data.m for RT_GENE). I wonder if it is available or not ? Thank you !

**Comment by Tobias-Fischer** [comment]
Hi, please send me an email.

**Comment by martinhoang11** [comment]
martinhoang11@gmail.com
Thank you !

**Comment by martinhoang11** [comment]
One more question, I've searched for UTMV data source but can not find the dataset. Do you know where was it stored or give me a link if possible :)

**Comment by martinhoang11** [comment]
Hi Tobi, I haven't received any emails from you about this issue. Did you sent it to me ?

**Comment by Tobias-Fischer** [comment]
Hi,
It seems like this project does what you want to do: https://github.com/yihuacheng/RT-Gene (although it's not from us and we cannot support MPII/UTVM; we focus on our own dataset).
