### ISSUE TITLE
Issue of not found files that "../rt_gene/model_nets/SFD/s3fd_facedetector.pth" "../rt_gene/model_nets/phase1_wpdc_vdc.pth.tar".

### ISSUE THREAD

**Issue by UlziibayarRepo** [Tobias-Fischer/rt_gene#103]
Hello, I'm trying to run the rt_gene_standalone. But An error occurred while the code was running. The error is not found these files
"../rt_gene/model_nets/SFD/s3fd_facedetector.pth" "../rt_gene/model_nets/phase1_wpdc_vdc.pth.tar". I've checked these files following path, so Absolutely don't have this path. How i solve this problem. Please help me.

**Comment by Tobias-Fischer** [comment]
Hi,

Can you please try running `python $HOME/rt_gene/rt_gene/scripts/download_models.py` (you might need to adapt the path), and then run the standalone script again?

If you still have issues, please copy+paste the exact commands that you are running, and the complete output.


Best, Tobi

**Comment by UlziibayarRepo** [comment]
> Hi,
> 
> Can you please try running `python $HOME/rt_gene/rt_gene/scripts/download_models.py` (you might need to adapt the path), and then run the standalone script again?
> 
> If you still have issues, please copy+paste the exact commands that you are running, and the complete output.
> 
> Best, Tobi

I've did as you said. It's working great. Thank you so much. This system that you made has become a really robust system. GOOD LUCK GUYS!!

**Comment by Tobias-Fischer** [comment]
That's great to hear, thanks for your feedback!
