### ISSUE TITLE
DenseNet and ReseNet PyTorch blink models

### ISSUE THREAD

**Issue by SohilZidan** [Tobias-Fischer/rt_gene#105]
Hello,

where I can find the pretrained models on DenseNet and ResNet backbones? I am trying to use estimate_blink_standalone.py

Best

**Comment by Tobias-Fischer** [comment]
Hiya,

Currently we do not have pretrained models (unless you have some @ahmed-alhindawi?). You can easily use the train_model.py in the rt_bene_model_training folder and change the `model_base` to train a model yourself though:
https://github.com/Tobias-Fischer/rt_gene/blob/6eb7c32ff123a3f7b13bc9a492080a72158b14b0/rt_bene_model_training/pytorch/train_model.py#L84-L86

Closing here - let us know if you have more questions.

**Comment by ahmed-alhindawi** [comment]
Sorry, there aren't any publically available Pytorch models for DenseNet or ResNet at the moment. But Tobias is right - it'll be easy to train if you'd like to.
