### ISSUE TITLE
The link to download datatset have just down

### ISSUE THREAD

**Issue by vuthede** [Tobias-Fischer/rt_gene#110]
Could you up the server again? The link to download datatset have just down 2 minutes ago.
Thank you.

**Comment by Tobias-Fischer** [comment]
Both links (https://zenodo.org/record/2529036#.YYGw2S8Rqjg and https://imperialcollegelondon.app.box.com/s/t8iu1qf6bsx87lcp26lcw4hkzm2i4rv4) work fine for me. Which one doesn't work?
