### ISSUE TITLE
How to convert the 2D gaze vector in the output into a 3D gaze vector?

### ISSUE THREAD

**Issue by DarkstartsUp** [Tobias-Fischer/rt_gene#111]
Hello, in estimate_gaze_standalone.py, how can I get the 3D gaze vector (x, y, z) in the camera coordinate system from the 2D vector in the output? Thanks!

**Comment by Tobias-Fischer** [comment]
Hi,

Does that help?
https://github.com/Tobias-Fischer/rt_gene/blob/aef31be7031f2f93cdd71e603d73375c0fcd4887/rt_gene/src/rt_gene/gaze_tools.py#L131-L133

If not feel free to reopen.
