### ISSUE TITLE
Question regarding reducing image size from 224x224 to 36x60

### ISSUE THREAD

**Issue by GrantZheng86** [Tobias-Fischer/rt_gene#113]
Hello there,

Happy holidays to you all!

I noticed a change in data input size from 224x224 to 36x60 in [this file](https://github.com/Tobias-Fischer/rt_gene/blob/aef31be7031f2f93cdd71e603d73375c0fcd4887/rt_gene_model_training/pytorch/rtgene_dataset.py#L10) at line 20. I am wondering if this change will cause the accuracy of the prediction to change? Also, what's the original rationale for using 224x224 images? 

Thanks in advance for helping out!

**Comment by Tobias-Fischer** [comment]
Hi @GrantZheng86,

Happy holidays to you, too!

The input images have a resolution of 36x60. As far as I remember, @ahmed-alhindawi (who implemented the PyTorch version) told me that the backbone at some stage required a minimum resolution of 224x224, so the images originally were upsampled to 224x224. This minimum resolution does not seem to be required anymore.

As the original images only had 36x60 resolution anyhow, the predictions should not change (significantly) as the information content is the same.

Hope that helps!

Best, Tobi

**Comment by GrantZheng86** [comment]
Thanks a lot for your quick response! That makes sense, the original VGG, without any modification, does require 224 image size.
