### ISSUE TITLE
Where to find research's night dataset

### ISSUE THREAD

**Issue by ljy1998-cool** [Tobias-Fischer/rt_gene#114]
cannot find this dataset,could you help me?

**Comment by Tobias-Fischer** [comment]
This dataset is by Andrej Fogelton.

All the data and software are under GPLv3 license, by using them you agree to the license, if you do not agree, please do not use it https://www.gnu.org/licenses/gpl-3.0.en.html 

https://www.blinkingmatters.com/files/upload/research/RN.zip

**Comment by ljy1998-cool** [comment]
thank you so much. helps a lot!!!
