### ISSUE TITLE
Evaluation metric for eyeblink8

### ISSUE THREAD

**Issue by alexzeng1206** [Tobias-Fischer/rt_gene#117]
Thanks for your great work. I have some questions about the evaluation metric of eyeblink detection.
If I understand correctly, when calculating AP, the true positives and false positives are assigned in a per-frame manner. In other words, the eyeblink detection task is regarded as a binary classification task within each image during evaluation. We don't need to calculate temporal IoU like AP in general action detection task. Is that right?

**Comment by Tobias-Fischer** [comment]
Yes that’s the way that we evaluated on eyeblink8. However note that other papers have used temporal IoU if I remember correctly - please check the paper that proposed the dataset.
