### ISSUE TITLE
Masking eyetracking glasses region

### ISSUE THREAD

**Issue by ChiwoongLEE** [Tobias-Fischer/rt_gene#119]
Hello. First of all, thank you for your excellent research.

Hello. First of all, thank you for your excellent research.

Analyzing the code for GlassesCompletion.py, I found out that `original/face/face.png` and` mask/mask_overlay.png` are needed.

I could not find any information on how to create an image in the mask folder in that github. If possible, can I ask you about the detailed method?

**Comment by Tobias-Fischer** [comment]
Please see the paper for information how the masks were created - in a nutshell, we used OptiTrack to obtain the pose of the glasses and, given a 3D model of the eyetracking glasses, projected the model in the camera image, which provides you with the mask. We do not provide code for the generation of the masks.

**Comment by ChiwoongLEE** [comment]
Thank you for the good information.
If you don't mind, could you provide me with a code on how to project the model onto the camera image?

**Comment by Tobias-Fischer** [comment]
This should be fairly straightforward using opencv. Unfortunately I don’t have any more code for rt-gene than what’s provided here.
