### ISSUE TITLE
UT Multi-view gaze dataset usage

### ISSUE THREAD

**Issue by lyyiangang** [Tobias-Fischer/rt_gene#12]
Hi Sir,
Excited to see your gaze project. the readme says you use UT Multi-view dataset, clould you please provide some code about the pre-processing  of this dataset?  I am facing a problem about the converting of gaze vector to yaw and pitch angle.
In the dataset, s00/test/000_left.csv contain following lines:
```
0.657246  0.0937712  -0.74782  -0.0511348  -0.548227  -0.0143822  -7.6967E-06  1.92417E-06  600
```
the first 3 numbers '0.657246  0.0937712  -0.74782' is gaze direction in camera coordinate, I convert it to yaw and pitch directly like this:
```
   # gaze direction (gx, gy, gz)
    yaw = np.arctan2(-gx, -gz)
    pitch = np.arcsin(-gy)
```  
But it seems not correct after I plot the gaze vector to original image. Could you give some tips or code? 

Thanks very much.

**Comment by Tobias-Fischer** [comment]
Hi @lyyiangang,
Please get in touch via e-mail and I'll send you some matlab pre-processing code.

Best, Tobias

**Comment by lyyiangang** [comment]
> Hi @lyyiangang,
> Please get in touch via e-mail and I'll send you some matlab pre-processing code.
> 
> Best, Tobias

Thanks. I have send an E-mail to t.fischer@imperial.ac.uk. waiting for your reply.

**Comment by aliabid2243** [comment]
Hi @Tobias-Fischer, Please if you could send me the code as well, I will really appreciate that. I have already sent you an email regarding this. my email (aali.abidkhan@gmail.com).
Hoping for a response from you. 
Thank you.
Regards

**Comment by leolordwz** [comment]
Hi, @Tobias-Fischer, this is Zhen and I have sent an email to you from (sxxxxxzhen@gmail.com). Could you please share with me the codes? Thank you very much for your time and help.

**Comment by gusong** [comment]
Hi,  @Tobias-Fischer, I can not find the way from the raw image to the test image in UT Multi-view gaze dataset. Could you please share with me the codes? Thanks a lot. My email is gusong@cap.edu.cn

**Comment by err-or** [comment]
Hi @Tobias-Fischer, can you please share the codes with me? 
My email: 19zm5@queensu.ca
