### ISSUE TITLE
Calculation value for head pose

### ISSUE THREAD

**Issue by ChiwoongLEE** [Tobias-Fischer/rt_gene#120]
The head pose translation and head_rotation values in _label_headpose_detailed.txt_ were checked.
I wonder how the head pose value of _label_combined.txt_ is related to these and how it is calculated.

For example, some of the s000_glasses data.

**1) label_headpose_detailed.txt**
1, [2.158416075617466, 0.09736256047809277, 0.2472418433954524], [-0.09560485024463679, 0.29910425523996975, -0.16486545411663833], 1504190788.51

**2) label_combined.txt**
1, [0.164865454117, -0.29910425524], [-0.119121529839, 0.162986524399], 1504190788.51

++
Additionally, I wonder why the quaternion rotation is made for the gaze value.
(https://github.com/Tobias-Fischer/rt_gene/blob/2740404431e5853f47a9fc25e4ce339b2bb6953a/rt_gene/scripts/estimate_gaze.py#:~:text=def%20publish_gaze(,*euler_angle_gaze))
Shouldn't quaternion rotation be (roll, pitch, yaw) with the Euler angle relative to the head pose?

**Comment by Tobias-Fischer** [comment]
Hi @ChiwoongLEE,
Many thanks for your interest in RT-GENE. For your first question, please see https://github.com/Tobias-Fischer/rt_gene/issues/64

Regarding your second question, this rotation is relative to the head pose: https://github.com/Tobias-Fischer/rt_gene/blob/2740404431e5853f47a9fc25e4ce339b2bb6953a/rt_gene/scripts/estimate_gaze.py#L159-L160

**Comment by ChiwoongLEE** [comment]
Thank you for always being interested and explaining kindly.
Your study was impressive to me who was interested in gaze estimation.

I'm really sorry, but it's hard to understand the code intuitively.
https://github.com/Tobias-Fischer/rt_gene/blob/2740404431e5853f47a9fc25e4ce339b2bb6953a/rt_gene/scripts/estimate_gaze.py#L159-L160:~:text=t.header.frame_id%20%3D,world_gaze%22%20%2B%20str(subject_id)

In the case of **gaze_phi, gaze_theta in label_combined.txt**, can I say that the gaze direction obtained from the pupil core is obtained by performing quaternion rotation by the head rotation?
