### ISSUE TITLE
additional question

### ISSUE THREAD

**Issue by ChiwoongLEE** [Tobias-Fischer/rt_gene#121]
Thank you for always being interested and explaining kindly.
Your study was impressive to me who was interested in gaze estimation.

I'm really sorry, but it's hard to understand the code intuitively.
https://github.com/Tobias-Fischer/rt_gene/blob/2740404431e5853f47a9fc25e4ce339b2bb6953a/rt_gene/scripts/estimate_gaze.py#L159-L160:~:text=t.header.frame_id%20%3D,world_gaze%22%20%2B%20str(subject_id)

In the case of **gaze_phi, gaze_theta in label_combined.txt**, can I say that the gaze direction obtained from the pupil core is obtained by performing quaternion rotation by the head rotation?

_Originally posted by @ChiwoongLEE in https://github.com/Tobias-Fischer/rt_gene/issues/120#issuecomment-1423577320_

**Comment by Tobias-Fischer** [comment]
If I remember correctly, the gaze_phi and gaze_theta in the `label_combined.txt` were obtained purely by the wearable eyetracker. One value indicates eye gaze left/right, and the other eye gaze up/down.

The code you linked then uses the estimated eye gaze and puts it in the frame of reference of the estimated head pose. See http://wiki.ros.org/tf for more details.
