### ISSUE TITLE
facial landmark detection module

### ISSUE THREAD

**Issue by qiuzhewei** [Tobias-Fischer/rt_gene#124]
Hello,
Thank for your great work!
I am trying to using the eye blinking detection script on my own images. It seems that the model takes two inputs, left eye and right eye, but the landmark detection module is missing from your repo. Is there anythere I can find it?
And also, do you have light weight pretrained model, i.e. mobilenetV3, to speed up the whole process?

**Comment by Tobias-Fischer** [comment]
Many thanks for your interest in our work!

You can find the landmark model here: https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene_standalone/estimate_gaze_standalone.py

We do not have other pre trained models besides the ones mentioned in the repository. But all data is available so it should be easy to modify the code to train your own.

Feel free to reopen if you have more questions.
