### ISSUE TITLE
details about other dataset performence

### ISSUE THREAD

**Issue by ackness** [Tobias-Fischer/rt_gene#13]
Hi. @Tobias-Fischer 

I noticed there are some evaluation results on MPIIGaze and UT Multi-view dataset on this link: https://paperswithcode.com/paper/rt-gene-real-time-eye-gaze-estimation-in

|Task | Dataset | Model | Metric name | Metric value | Global rank | 
|-- | -- | -- | -- | -- | -- | 
|Gaze Estimation | MPII Gaze | RT-GENE 2 model ensemble | Angular Error | 4.6 | # 2 | 
|Gaze Estimation | MPII Gaze | RT-GENE single model | Angular Error | 4.8 | # 3 | 
 | Gaze Estimation | MPII Gaze | RT-GENE 4 model ensemble | Angular Error | 4.3 | # 1 | 
 | Gaze Estimation | RT-GENE | RT-GENE 4 model ensemble | Angular Error | 7.7 | # 1 | 
 | Gaze Estimation | UT Multi-view | RT-GENE 4 model ensemble | Angular Error | 5.1 | # 1|

But I not found details about these dataset in this repo. Can you provide more details or codes? 
That would give us a lot of helps.

Thanks for this excellent work!

**Comment by Tobias-Fischer** [comment]
Hi,
Thanks a lot for your interest in our work! The main focus of our work is on evaluating our new network architecture our own dataset. Therefore, there is no code for MPIIGaze and UT Multi-view contained here. There are no plans of adding code to process/evaluate other datasets.
I will close this issue for now - please also see https://github.com/Tobias-Fischer/rt_gene/issues/11.

Best, Tobias
