### ISSUE TITLE
gaze vector

### ISSUE THREAD

**Issue by Lzeo** [Tobias-Fischer/rt_gene#17]
we have two gaze vectors from both eyes, do you compute the mean of both gaze vectors and use it as the label ?

**Comment by Tobias-Fischer** [comment]
Hi @Lzeo, you can find the computation of the mean here: https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/scripts/estimate_gaze.py#L100-L106

If you have any further questions, please re-open this issue.

Best, Tobias
