### ISSUE TITLE
Face boxes on the side can be discarded

### ISSUE THREAD

**Issue by Twarz** [Tobias-Fischer/rt_gene#18]
Hey,

I had a problem with the half part of my image (from webcam) where face boxes were discarded.

This comes from the following line:
https://github.com/Tobias-Fischer/rt_gene/blob/065443dc366f3241aaf8f021802bd8728e39d089/rt_gene/src/rt_gene/extract_landmarks_method.py#L158

You have to revert indexes when you check x and y with the border of the image:
`if x_left_top > 0 and y_left_top > 0 and x_right_bottom < image.shape[1] and y_right_bottom < image.shape[0] and confidence > 0.8:`

Best,
Kévin

**Comment by Tobias-Fischer** [comment]
Hi @Twarz,
Thanks for reporting this issue. Could you please open a pull request? I will merge it.

@ngageorange: This might be the long-running issue you've been running into.

Thanks and best wishes,
Tobi

**Comment by Twarz** [comment]
Done! Hope this will help you :)

Best,
Kévin

**Comment by Tobias-Fischer** [comment]
You opened the PR in the wrong repo (your local copy). Could you please open it in this repo?

**Comment by Twarz** [comment]
Sorry for this, it should be ok now :)

**Comment by Tobias-Fischer** [comment]
Thanks @twarz for the fix!
