### ISSUE TITLE
setup instructions

### ISSUE THREAD

**Issue by cshreyastech** [Tobias-Fischer/rt_gene#25]
I am exploring eye tracking solutions for one of my research work. 
Your research solution seems to be interesting. 
Can you let me know the setup instructions?

Thanks,

**Comment by Tobias-Fischer** [comment]
Hi,
Thank you for your interest in our work. Please check the main `README.md` file, as well as the `README.md` files within the subdirectories depending on what you are trying to achieve. These files contain detailed instructions to train & run our network.

I am closing this issue for now, please feel free to re-open if you have more concrete questions.

Best, Tobias
