### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by godfreylui** [Tobias-Fischer/rt_gene#27]
Hi Tobias,

I am doing my MSc Project with Hyung Jin and am planning on using the rt_gene for eye tracking. My laptop doesnt have a GPU, I am just wondering whether it will still run? And that it would just be a lot slower with the CPU?

Best wishes,

Godfrey

**Comment by Tobias-Fischer** [comment]
Hi Godfrey,
Yes it'll still run (but it'll be super slow). Change the parameters in https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/launch/estimate_gaze.launch#L16-L18 to the mentioned ones for CPU usage.
