### ISSUE TITLE
Improve computational speed for multi person estimation

### ISSUE THREAD

**Issue by Tobias-Fischer** [Tobias-Fischer/rt_gene#34]
At the moment the frame rate drops considerably when more than 3 people or so are in the scene. Let's find out where the bottleneck is and improve the speed.

**Comment by Tobias-Fischer** [comment]
@ngageorange and I have been working on this - the https://github.com/Tobias-Fischer/rt_gene/tree/modularised branch uses https://github.com/cleardusk/3DDFA for landmark extraction which was the main bottleneck. The overall pipeline is much faster now.

There is still room for improvement by passing batches of images to the gaze estimator, rather than doing the inference one-by-one.

**Comment by ngageorange** [comment]
batching can now be found in the modularised branch. Multiperson setup works nicely there too.
