### ISSUE TITLE
Provide standalone (non-ROS) script

### ISSUE THREAD

**Issue by Tobias-Fischer** [Tobias-Fischer/rt_gene#37]
So far, it is rather difficult to run the pipeline without ROS. For the computer vision community, it would be much easier to read an image from disk and predicting the gaze on this image.

This is now possible (still beta though) thanks to a lot of refactoring. The script can be found here: https://github.com/Tobias-Fischer/rt_gene/blob/modularised/rt_gene/scripts/estimate_gaze_standalone.py

If anyone is using this, please let me know if you have feedback.

**Comment by ngageorange** [comment]
This is now in the modularised branch...
