### ISSUE TITLE
Use trained model for inference

### ISSUE THREAD

**Issue by sahilrider** [Tobias-Fischer/rt_gene#38]
I have trained the model as per the rt_gene_training folder. I have saved the final models for each folds. I want to use these models to test on new images. How to do it? Which model to use?

I don't want to go through the whole ros pipeline.
Thanks

**Comment by Tobias-Fischer** [comment]
Hi,
Please see the comments in #37; in particular you can now simply use https://github.com/Tobias-Fischer/rt_gene/blob/modularised/rt_gene/scripts/estimate_gaze_standalone.py
(don't forget to change branches). The script allows you to specify an image path as well as which model files to use.

Best, Tobias

**Comment by Tobias-Fischer** [comment]
See also https://github.com/Tobias-Fischer/rt_gene/blob/modularised/rt_gene_standalone/README.md
