### ISSUE TITLE
detailed training setup

### ISSUE THREAD

**Issue by FigaroK** [Tobias-Fischer/rt_gene#42]
Hi, I ran your code without any modification. But the results of evaluation on your dataset are not ideal, could you provide some hints? Thanks a lot.

**Comment by ngageorange** [comment]
Could you please be a little more specific? What do you mean not ideal?

The results of the original code (initial commit) to this repository is in the paper...

**Comment by FigaroK** [comment]
Maybe there was a problem when I downloaded the dataset, I will download it again and check it.

**Comment by FigaroK** [comment]
thanks a lot, it's solved
