### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by trueivorian** [Tobias-Fischer/rt_gene#47]
I'm having trouble building the rt_gene project. I have followed the software installation steps (including installing ros melodic and all the necessary packages) and received the following error messages:

Installation attempt on an Ubuntu 18.04 Virtual Machine:
![image](https://user-images.githubusercontent.com/15149274/69421606-62bb3180-0d19-11ea-8c5a-af45d52b785c.png)

Installation attempt on the Windows Subsystem for Linux (Ubuntu 18.04):
![image](https://user-images.githubusercontent.com/15149274/69421647-7b2b4c00-0d19-11ea-9e44-aca1a4533cad.png)

**Comment by Tobias-Fischer** [comment]
Hi there,
for the Ubuntu VM, try `sudo apt-get install python-catkin-pkg`. Not sure what happens in the WSL; it seems that ROS is not installed successfully.

All that being said, I do not recommend running RT-GENE in a virtual machine / subsystem, as the access to GPU will probably not work, which will make it very slow.

Also, do you need the ROS version? There is a standalone version now which might be better suited.

Best, Tobias

**Comment by trueivorian** [comment]
Hi,
  I have new output following a fresh install using sudo apt-get install python-catkin-pkg.
Now one of the packages have been built successfully, however there is apparently a non-existing file rt_gene/scripts/estimate.blink.py. Any suggestions for fixes.

Regards,
Osanne Gbayere

**Comment by Tobias-Fischer** [comment]
Hi,
Sorry, that was a bug introduced when working on the blink estimation pull request (#43). I fixed it in https://github.com/Tobias-Fischer/rt_gene/commit/bd068bfdb3e62a055dd0ebbb7632d5b096b46093.

Best, Tobias

**Comment by trueivorian** [comment]
All working now!

Thanks

**Comment by Tobias-Fischer** [comment]
Great, very happy to hear that. See https://github.com/Tobias-Fischer/rt_gene/commit/d1ba93924310dc4388ad09bf97cb1d95228214a8 for the readme update of the problem you faced.
