### ISSUE TITLE
Update standalone script with head pose fixes

### ISSUE THREAD

**Issue by Tobias-Fischer** [Tobias-Fischer/rt_gene#48]

**Comment by sahilrider** [comment]
Hey Tobias, Can you tell me why previous headpose was wrong? and how does it fixed it?

**Comment by Tobias-Fischer** [comment]
Hi,
There was a mistake in how the face model was created and subsequently transformed from the camera coordinate frame into the ROS camera frame. See https://github.com/Tobias-Fischer/rt_gene/commit/9cde8128ba6f27869aff8e4f442253ccb500671c for more info and the actual fixes. Is that sufficient information?

Best, Tobias
