### ISSUE TITLE
unable to run catkin build

### ISSUE THREAD

**Issue by sudhanshu22gupta** [Tobias-Fischer/rt_gene#59]
`
pc-136@linux:~/catkin_ws$ cd $HOME/catkin_ws && catkin build

Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/pc-136/catkin_ws

Build Space:        [exists] /home/pc-136/catkin_ws/build
Devel Space:        [exists] /home/pc-136/catkin_ws/devel
Install Space:      [unused] /home/pc-136/catkin_ws/install
Log Space:          [exists] /home/pc-136/catkin_ws/logs
Source Space:       [exists] /home/pc-136/catkin_ws/src
DESTDIR:            [unused] None

Devel Space Layout:          linked
Install Space Layout:        None

Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False

Whitelisted Packages:        None
Blacklisted Packages:        None

Workspace configuration appears valid.

[build] Found '1' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Starting  >>> rt_gene                                                          

Errors     << rt_gene:make /home/pc-136/catkin_ws/logs/rt_gene/build.make.001.log
Traceback (most recent call last):
  File "/home/pc-136/catkin_ws/src/rt_gene/rt_gene/cfg/ModelSize.cfg", line 4, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
make[2]: *** [/home/pc-136/catkin_ws/devel/.private/rt_gene/include/rt_gene/ModelSizeConfig.h] Error 1
make[1]: *** [CMakeFiles/rt_gene_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/pc-136/catkin_ws/build/rt_gene; catkin build --get-env rt_gene | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << rt_gene:make           [ Exited with code 2 ]                    
Failed    <<< rt_gene                [ 0.2 seconds ]                           
[build] Summary: 0 of 1 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.2 seconds total.                                            
`

**Comment by ngageorange** [comment]
You don't seem to have a complete ROS install as evident by
`import rospkg
ModuleNotFoundError: No module named 'rospkg'`

If you run `sudo apt-get install python-rospkg`
then re-run `catkin build` it'll work.

Alternatively:
`sudo pip install -U rospkg` if you're not on an Ubuntu platform.

Let us know if you have any other problems.

**Comment by sudhanshu22gupta** [comment]
I'm running python 3.7.4. I don't know why it's searching in 2.7

**Comment by Tobias-Fischer** [comment]
ROS melodic by default uses Python2. Using Python3 is possible but quite tricky - please check on Google if this is what you want. If you use the standalone version of RT-GENE you can use Python3. 

Note that in April ROS noetic will be released which will run with Python3.

Does that help?
