### ISSUE TITLE
headpose in dataset from 3D to 2D

### ISSUE THREAD

**Issue by AaboutL** [Tobias-Fischer/rt_gene#64]
Headpose in label_combined.txt is 2-dimensional， while in label_headpose_detailed.txt is 3-dimensional。If I want to train on MPIIGaze， how to transform headpose from 3D to 2D？

**Comment by Tobias-Fischer** [comment]
Hi,
Please see https://github.com/Tobias-Fischer/rt_gene/blob/3f45c55aa5801a5288e1f3367d1197f4fc6309cd/rt_gene/src/rt_gene/gaze_tools.py#L12
Basically, we discard the roll (of yaw-pitch-roll) after aligning the face image. Note that we unfortunately cannot provide support for other datasets.

Best, Tobias
