### ISSUE TITLE
Where is model definition in Pytorch branch?

### ISSUE THREAD

**Issue by gd2016229035** [Tobias-Fischer/rt_gene#65]
Where is "gaze_estimation_models_pytorch.py"? The PyTorch branch may work now or still in experimenting?
Thanks~

**Comment by ngageorange** [comment]
`gaze_estimation_models_pytorch.py` is in the src folder of rt_gene of the `pytorch_training` branch.

Please see the pull request as to the state of the pytorch effort. As it hasn't been pulled into master, it's definitely still experimental.
