### ISSUE TITLE
Where to get s3fd_facedetector.pth 

### ISSUE THREAD

**Issue by huxian0402** [Tobias-Fischer/rt_gene#69]
Good work. When I try to reproduce the results in your paper,  I found no s3fd_facedetector.pth  for pytorch_training. Could you please provide me with a download link?  Thanks a lot. @Tobias-Fischer @ngageorange @hjchang @dvarnai @Twarz

**Comment by Tobias-Fischer** [comment]
Hi @huxian0402, please see https://github.com/Tobias-Fischer/rt_gene/commit/798d31bffe29fdb0142bfc46604e611ef5ccc020
The required files with download links are listed in https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/scripts/download_models.py (just run that script to download all of them in the proper location).

Let us know if you have further issues.

Best, Tobias

**Comment by huxian0402** [comment]
You really help me a lot. Thanks again.
