### ISSUE TITLE
Separate external libraries from internally developed files

### ISSUE THREAD

**Issue by ahmed-alhindawi** [Tobias-Fischer/rt_gene#70]

**Comment by Tobias-Fischer** [comment]
Do you have any plans on doing this @ahmed-alhindawi? Otherwise I suggest to close.

**Comment by ahmed-alhindawi** [comment]
It's quite down my list of things to do to be honest - I probably agree with it on a spiritual level, and while the mind is willing, the body is soft and squiggy....
