### ISSUE TITLE
download_models.py

### ISSUE THREAD

**Issue by ICMoon527** [Tobias-Fischer/rt_gene#77]
when I run this script(rt_gene/rt_gene/scripts/download_models.py), raise ConnectTimeout Error as below:
`requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='imperialcollegelondon.app.box.com', port=443): Max retries exceeded with url: /public/static/zblg37jitf9q245k3ytad8nv814nz9o8.model (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb5097e950>, 'Connection to imperialcollegelondon.app.box.com timed out. (connect timeout=10)'))`

And I have failed to directly open the url either. 

How to fix it? Thanks for your time.

**Comment by Tobias-Fischer** [comment]
Hi,
Where are you based? I can download the file just fine on my computer.

**Comment by ICMoon527** [comment]
Hi, I'm based in China. I can also access external websites such as YouTube. 
After trying many times with different tools, models can be downloaded slowly( 5 KBps) which means it may take one day with the browser. Thus, if I can't download them all quickly, I wonder which model is needed to run the whole training steps? (Pytorch, MPIIGaze)

And another question is, 
`from gaze_estimation_models_pytorch import GazeEstimationModelResnet18, GazeEstimationModelVGG, GazeEstimationModelPreactResnet`
Will this line work after downloading the models or this line has nothing to do with the models?
I can't find a directory or python file named gaze_estimation_models_pytorch.

**Comment by Tobias-Fischer** [comment]
Hi,
This file is located in https://github.com/Tobias-Fischer/rt_gene/tree/master/rt_gene/src/rt_gene

Let me know if you are not able to download the models in the next few days and I will try and setup a suitable mirror.

For the training steps, please see https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene_model_training/README.md
For MPII, the code to generate the dataset is located in https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene_model_training/pytorch/utils/GenerateMPIIH5Dataset.py

**Comment by ICMoon527** [comment]
Thanks for your detailed explanation.

The connection broke after little part of a model being downloaded. Tried to reconnect but found no file again. A friend of mine faced the same situation yesterday. 

Things changed this morning. Speed rise from 5KB - 10KB(me) and 5KB - 1000KB(my friend). He downloaded successfully. Amazing and don't know what happened. But at least this problem is fixed...

**Comment by Tobias-Fischer** [comment]
Great, thanks for letting me know!

**Comment by kaikaizhu** [comment]
@Tobias-Fischer 
I try to download,but failed. Can you put model files on https://drive.google.com/ ?
I want to test the eye_blink. Thanks a lot!

**Comment by Tobias-Fischer** [comment]
The files are now available at: https://drive.google.com/drive/folders/1cdOlCoXBIv-KxBGPP88oijd85uc5XVGF?usp=sharing
