### ISSUE TITLE
model architecture 

### ISSUE THREAD

**Issue by aunsid** [Tobias-Fischer/rt_gene#79]
I was reading the paper and the source code for creating the model [using pytorch](https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/src/rt_gene/gaze_estimation_models_pytorch.py). I could not find the head pose estimation net as mentioned in figure 2 (that takes in the face as the input). Secondly, I just wanted to confirm whether you use Resnet18 and/or VGG16 on the left and right eye images then pass the outputs to the GazeEstimationAbstractModel.

**Comment by aunsid** [comment]
And in the same file there are two typos.  line 42 and line 46 self.x_l() and self.x_r()

**Comment by Tobias-Fischer** [comment]
Hi @aunsid, thank you for your interest in RT-GENE!

1) In this repo, we do not provide code for the head pose net as described in the paper. Instead, we use (details in https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/README.md)
1.1) S3FD face detector (https://github.com/1adrianb/face-alignment)
1.2) Face alignment (https://www.pyimagesearch.com/2017/05/22/face-alignment-with-opencv-and-python/)
1.3) 3DDFA face landmark extraction (https://github.com/cleardusk/3DDFA)
1.4) PnP to align a face model with the extracted landmarks
2) In the paper, we show results for VGG16. If you want faster inference times, we recommend using Resnet18 instead.

Please let us know if you have additional questions - closing here for now.
