### ISSUE TITLE
type of left-right eyes image

### ISSUE THREAD

**Issue by TranThanh96** [Tobias-Fischer/rt_gene#82]
I am wondering about this. I used matplotlib to visual left-right eyes and this is the result. can you explain this?
![image](https://user-images.githubusercontent.com/26323599/94884446-b3ea9480-0497-11eb-8eb0-67adbd64750d.png)

**Comment by Tobias-Fischer** [comment]
I'm sorry but you don't provide nearly enough information. What are you plotting / doing, what are the commands you execute, what is the input etc? 
Feel free to reopen once more information is available.

**Comment by TranThanh96** [comment]
yes, It was my fault. I visualized the normalized image, that why I got those pictures. Thank you!.
By the way, I have one more question: I am confusing about the function "def get_endpoint(theta, phi, center_x, center_y, length=300)"
I know that we can get the theta and phi by trained models, but can u suggest any tutorial to understand theta and phi in the gaze estimation problem? I am confusing about this.

**Comment by Tobias-Fischer** [comment]
Could you please provide the code to produce those images? Is our standalone script working fine for you? I'm afraid we can't support your own code.

theta and phi simply refer to looking left/right and up/down (just the eye gaze)

**Comment by TranThanh96** [comment]
I just draw the subject.left_eye_color and subject.right_eye_color in your code, that why I archive those above pictures. And I realized that you normalize left_eye_color and right_eye_color by this function: 
![image](https://user-images.githubusercontent.com/26323599/94890579-cbcb1400-04a9-11eb-8455-8c38da286253.png)
so all I need is draw the left_eye_color and right_eye_color before u normalize, that's all.

Can you explain more detail about theta and phi?

**Comment by TranThanh96** [comment]
maybe I am wrong, but I this the issue about eyes images, so its OK
