### ISSUE TITLE
Generating Eye Patches Issue and Question

### ISSUE THREAD

**Issue by GrantZheng86** [Tobias-Fischer/rt_gene#84]
Hi there,

Thanks for this great project! 

_**Here's the Issue:**_
As I was trying to train the CNN following the steps of README from the "_rt_gene/rt_gene_model_training/_" page. I encountered an error

 "_GenerateEyePatchesRTGENEDataset.py_" prompted an error saying that

> "'TrackedSubject' object has no attribute 'transformed_eye_landmarks'"

I double-checked the "_tracker_generic.py_" file, and there was indeed no "_transformed_eye_landmarks_" object in the "_TrackedSubject_' class (but there's a local variable with the same name in "get_eye_image_from_landmarks" function). When running this "_GenerateEyePatchesRTGENEDataset.py_" file, I copied the face images from nonglass folder founded here https://zenodo.org/record/2529036#.X8clOllKg1g (I think this should contain the right images). Could there a bug in the generating eye patch code?

_**Here's the question:**_
As I was going through the dataset, I was also wondering if the  "_GenerateEyePatchesRTGENEDataset.py_" will produce the same images as in the "_s0XX_glasses/inpainted/left_"  (and also /right)? Also, will the next step in the README:

> Compile the left_new and right_new patches along the labels into a h5 file using GenerateRTGENEH5Dataset.py, optionally augment the patches here to make it as similar to prepare_dataset.m from the tensorflow preparation stage.

output the same file as the "_Label_combined.txt_" in the folder "_s0XX_glasses/_" ? 

Thanks in advance for helping out!

**Comment by Tobias-Fischer** [comment]
Hi there,

Many thanks for reporting this issue! The error stems from some recent refactoring and we must not have checked the GenerateEyePatches file. I just fixed your problem in the master branch (https://github.com/Tobias-Fischer/rt_gene/commit/afba793617a78a5cfc346d523907c9c972a2c4ae), please pull the latest code and you should be good to go.

Regarding your question: The images won't be exactly the same. The images that are contained in the dataset are extracted using a much older version of RT-GENE, so there will be some small differences. I'm not sure whether it creates a Label_combined.txt - @ahmed-alhindawi any hints?
