### ISSUE TITLE
rt_gene dataset!

### ISSUE THREAD

**Issue by kimtaejun97** [Tobias-Fischer/rt_gene#86]
Does one face image correspond to one frame of the video?

In other words, is it a continuous image(video)?

**Comment by ahmed-alhindawi** [comment]
They're mostly continuous with occasional breaks - the data cleaning part of the paper stipulated that the images corresponding to extreme head angles were removed as the eye patches would have been obscured by the nasal ridge. I hope that helps.
________________________________

**Comment by Tobias-Fischer** [comment]
Yes, unfortunately you cannot assume that the images are continuos. We also filtered out frames  where the eyetracker confidence dropped etc.

**Comment by kimtaejun97** [comment]
Thank you
