### ISSUE TITLE
About multiple persons in one image

### ISSUE THREAD

**Issue by lindayuanyuan** [Tobias-Fischer/rt_gene#87]
Hi,
When I processed the pictures that have multiple persons in one image, It seemed that it processed multiple persons. However, only the results of the last person processed was saved. How to set up saving all the results of the same image? thanks.

**Comment by Tobias-Fischer** [comment]
Hello, could you please let us know which exact scripts you used? This will help to narrow down the problem.

**Comment by lindayuanyuan** [comment]
> Hello, could you please let us know which exact scripts you used? This will help to narrow down the problem.

Hi, I am using the standalone version. Thanks for the reply.

**Comment by lindayuanyuan** [comment]
> Hello, could you please let us know which exact scripts you used? This will help to narrow down the problem.

estimate_gaze_standalone.py

**Comment by Tobias-Fischer** [comment]
Hi, simply add the `idx` to the filename in https://github.com/Tobias-Fischer/rt_gene/blob/8aabdd34d9dccef69a9044a61494efb0695b333d/rt_gene_standalone/estimate_gaze_standalone.py#L93 and similarly the `subject_id` to the filename in https://github.com/Tobias-Fischer/rt_gene/blob/8aabdd34d9dccef69a9044a61494efb0695b333d/rt_gene_standalone/estimate_gaze_standalone.py#L120

It would be great if you contribute this in a pull request, the change should be straightforward.

**Comment by lindayuanyuan** [comment]
> Hi, simply add the `idx` to the filename in
> 
> https://github.com/Tobias-Fischer/rt_gene/blob/8aabdd34d9dccef69a9044a61494efb0695b333d/rt_gene_standalone/estimate_gaze_standalone.py#L93
> 
> and similarly the `subject_id` to the filename in
> https://github.com/Tobias-Fischer/rt_gene/blob/8aabdd34d9dccef69a9044a61494efb0695b333d/rt_gene_standalone/estimate_gaze_standalone.py#L120
> 
> It would be great if you contribute this in a pull request, the change should be straightforward.

Thanks for the reply. I would love to contribute. I have made changes accordingly. Not sure if the pull request works properly. 
Yuanyuan

**Comment by Tobias-Fischer** [comment]
Fixed by #88. Many thanks @lindayuanyuan!
