### ISSUE TITLE
Problems with estimating gaze using ROS

### ISSUE THREAD

**Issue by VeruGromnicova** [Tobias-Fischer/rt_gene#89]
Hello, I'm trying to run the method on video file using ROS according to the instructions in the readme. I am new with ROS so I am not really sure where is the problem. After roscore I launched "roslaunch rt_gene start_video.launch" and terminal output ended with INFO about start and stop frame. Then in another terminal I launched "roslaunch rt_gene estimate_gaze.launch". Model loaded correctly and also "Camera message received" appeared and meanwhile in the first terminal another INFO lines were added (opening VideoCapture with provider, video number of frames, video stream provider detected: videofile, FPS ). The information is correct, but the video does not appear on the screen at all. I added some prints into extract_landmarks_node.py, because I found out that the "Camera message received" output is from this script, and it turned out that the init method is completed but the process_image function is never executed, neither the following methods in script. So at that point nothing is happening and I do not know where the problem is. Thanks in advance for any advice.

**Comment by ahmed-alhindawi** [comment]
Hello,
I'm not familiar with `start_video.launch` as it uses an `video_stream_opencv` package. 
RT-GENE has a pipeline that starts with landmark extraction which is what the `extract_landmarks_node.py` performs. All that needs to happen is that the `start_video.launch` topics publish to the correct topics for the RT-GENE...

Have you tried it with a webcam using `start_webcam.launch` ? If that works, then it will be the case of ensuring that the topics from `start_video.launch` match up to what is expected from RT-GENE.

The output is a list of subjects with their headpose/gaze. Try:
- `rostopic list`: You should see `/subjects/gaze` and `/subjects/headpose`
- `rostopic echo /subjects/gaze`: You should see a live stream of the gaze and headpose estimation as the `estimate_gaze node` runs.

Lastly, have you tried the standalone script to make sure everything works?

**Comment by VeruGromnicova** [comment]
Thanks for your reply, yes I modified the video_file argument, [info] shows correct number of video frames, as you can see in attached screenshot. I also tried standalone script before ROS and it works fine. 
I am sorry, but I do not really understand, how can I find out if the start_video.launch topics publish to the correct topics for the RT-GENE. (Not sure if I understand you correctly, I am not a native speaker.)

![Screenshot from 2021-02-04 20-26-40](https://user-images.githubusercontent.com/72598436/106945490-23afab00-6728-11eb-8292-5d8df315c8aa.png)

**Comment by Tobias-Fischer** [comment]
Hi there,
Could you please send the output of `rostopic list` and `rostopic hz /kinect2/hd/image_color` as well as `rostopic Hz ? Your video only has 2350 frames

**Comment by VeruGromnicova** [comment]
Thanks for your reply, here is my output of `rostopic list`:

`kolder@ntb-kolder:~$ rostopic list
/gaze/gaze_extract_landmarks_new/parameter_descriptions
/gaze/gaze_extract_landmarks_new/parameter_updates
/image_raw
/image_raw/compressed
/image_raw/compressed/parameter_descriptions
/image_raw/compressed/parameter_updates
/image_raw/compressedDepth
/image_raw/compressedDepth/parameter_descriptions
/image_raw/compressedDepth/parameter_updates
/image_raw/theora
/image_raw/theora/parameter_descriptions
/image_raw/theora/parameter_updates
/kinect2/hd/camera_info
/kinect2/hd/image_color
/kinect2_stream/parameter_descriptions
/kinect2_stream/parameter_updates
/rosout
/rosout_agg
/subjects/faces
/subjects/gaze
/subjects/gazeimages
/subjects/headpose
/subjects/images
/subjects/landmarks
/tf
/tf_static
`
but the other two commands return `no new messages` indefinitely.
I always have roscore running.

**Comment by Tobias-Fischer** [comment]
Hi, my latest commit should solve your issues - please let me know if not. Thanks for reporting this bug!

**Comment by VeruGromnicova** [comment]
> Hi, my latest commit should solve your issues - please let me know if not. Thanks for reporting this bug!

It works fine now, thank you!
