### ISSUE TITLE
image type is .jpeg or .png

### ISSUE THREAD

**Issue by lindayuanyuan** [Tobias-Fischer/rt_gene#92]
When the im_path contains files with .jpeg or .png extensions, if I point the im_path to the folder, it seems that /rt_gene/rt_gene_standalone/estimate_gaze_standalone.py can't process those files. However, only if I point the im_path to the specific file, it works. What should I do if I want to process a batch of files with .jpeg or .png images? Thanks.

**Comment by Tobias-Fischer** [comment]
Hi,
Thanks for this report! `.png` should work fine - I just committed https://github.com/Tobias-Fischer/rt_gene/commit/b4f582eafb56d1de6c361f815aaca268802c8222 which should also allow `.png` extension. Previously the CaPiTaLiZaTiOn mattered, whereas that commit fixes this, too.

Please let me know if your issue is addressed.

**Comment by lindayuanyuan** [comment]
> Hi,
> Thanks for this report! `.png` should work fine - I just committed [b4f582e](https://github.com/Tobias-Fischer/rt_gene/commit/b4f582eafb56d1de6c361f815aaca268802c8222) which should also allow `.png` extension. Previously the CaPiTaLiZaTiOn mattered, whereas that commit fixes this, too.
> 
> Please let me know if your issue is addressed.

Thanks for the quick commit. Yes, it works now. When the image size is small, it throws errors like RuntimeError: Given input size: (512x1x2). Calculated output size: (512x0x1). Output size is too small, what is the size minimum requirement to process? thanks.

**Comment by Tobias-Fischer** [comment]
I'm not exactly sure - you can find the image sizes that we used in the paper. You can resize the images and do a trial and error investigation. It would also be good if you provide the full stack trace.

**Comment by lindayuanyuan** [comment]
resizing the image did the work. Thanks.
