### ISSUE TITLE
FileNotFoundError for: blink_model_resnet18_allsubjects0.model

### ISSUE THREAD

**Issue by balandongiv** [Tobias-Fischer/rt_gene#96]
When running the `estimate_blink_standalone`, the compiler return an error

> FileNotFoundError: [Errno 2] No such file or directory: '../rt_gene/model_nets/blink_model_resnet18_allsubjects0.model'

The final error trace originated from

https://github.com/Tobias-Fischer/rt_gene/blob/164e62cdc3c70bdc7d86df87e14d52cb331c923f/rt_gene/src/rt_gene/download_tools.py#L10

I notice the the `var` `blink_model_resnet18_allsubjects0.model` first declared along the following line

https://github.com/Tobias-Fischer/rt_gene/blob/4649628db4a0f5f209e18a2a82bdee1ccc63d5ee/rt_bene_standalone/estimate_blink_standalone.py#L77

May I know how to download  `var` `blink_model_resnet18_allsubjects0.model` . I have comb the `src` code, but there is no clear indicator on how to download this file.

**Comment by ahmed-alhindawi** [comment]
Thank you for bringing this to my attention.
It's a mistake in the `allsubjects0.model` - should be `allsubjects1.model`. I'll fix it now...

**Comment by balandongiv** [comment]
Hi @ahmed-alhindawi , thanks for fix suggestion. 

https://github.com/Tobias-Fischer/rt_gene/commit/c8b511d6fdc18bad648e05ce1903f0a6264561c0#diff-0a9fe43245a1fe1601c62675b266d0ea438415476060d44c866915576b47b2c2L77


However, the compiler still return the error

> FileNotFoundError: [Errno 2] No such file or directory: '../rt_gene/model_nets/blink_model_resnet18_allsubjects1.model'

**Comment by ahmed-alhindawi** [comment]
There were two issue with that string so I've fixed it. Sorry about that.

Just to note that the model files are parameters; note:
`parser.add_argument...` in `estimate_blink_standalone.py` file. Go ahead and add more models from where you run the script. You can add further models and they will be treated as an ensemble

**Comment by balandongiv** [comment]
Thanks, the issue is solved with the latest update.

Thanks for the extra note
