### ISSUE TITLE
ModuleNotFoundError: No module named 'rt_gene'

### ISSUE THREAD

**Issue by gv237-07** [Tobias-Fischer/rt_gene#99]
Hi. Thank you for your work.
I'm trying to run the standalone rt_gene demo on Google Colab, but I'm getting the error "ModuleNotFoundError: No module named 'rt_gene'" even after adding the source folder to the PYTHONPATH environment variable. This is my code if someone wants to replicate it:

`!pip install tensorflow-gpu numpy scipy tqdm torch torchvision Pillow opencv-python matplotlib`
`!git clone https://github.com/Tobias-Fischer/rt_gene.git`
`%cd rt_gene`
`%cd rt_gene_standalone`
`import os`
`os.environ['PYTHONPATH'] += "/content/rt_gene/rt_gene/src"`
`!python3 estimate_gaze_standalone.py --help`

**Comment by Tobias-Fischer** [comment]
Hi - to use rt_gene within the session, use 
```python
import sys
sys.path.insert(0, '/content/rt_gene/rt_gene/src')
```

This allows you to
```python
import rt_gene
```

If you want to run a python script within colab, you need to pass the PYTHONPATH:
```python
!PYTHONPATH=/content/rt_gene/rt_gene/src python3 estimate_gaze_standalone.py --help
```

**Comment by gv237-07** [comment]
Thank you very much @Tobias-Fischer

**Comment by FereshtehFeiz** [comment]
Hi, I did according to the following in the Colab, but still got this error: ModuleNotFoundError: No module named 'rt_gene'
`
!pip install tensorflow-gpu numpy scipy tqdm torch torchvision Pillow opencv-python matplotlib
!git clone https://github.com/Tobias-Fischer/rt_gene.git
%cd rt_gene
%cd rt_gene_standalone
import sys
sys.path.insert(0, '/content/rt_gene/rt_gene/src')
import rt_gene
!PYTHONPATH=/content/rt_gene/rt_gene/src python3 estimate_gaze_standalone.py --help
!python3 estimate_gaze_standalone.py --help
`
